
create table Employé(
Mat_emp varchar(5) primary key (Mat_emp),
Nom_emp char(20),
Prenom_emp  char(20),
Date_naiss_emp date,
Lieu_naiss_emp varchar(20),
Adresse_emp varchar(20),
Etat_civil_emp char(20),
Sexe_emp char(10),
Poids_emp int,
Taille_emp int,
Groupe_sang_emp char(2), 
RH_emp char(1),  
N_S_S_emp nvarchar(12), 
Mode_exercice Char(20),
Hor_travail_emp char(20),  
Date_recretement_emp date,
Date_départ_retraite date,
Cas_maladie char(20),
Service_national char(20),               
Tabagisme char(1),
ATCD_path char(20),     
Code_UF nvarchar (3) foreign key references Unité_fonctionnelle(Code_UF),
code_fonction varchar(10) foreign key references Fonction(Code_fonction),
ID_dossier varchar(05)foreign key references Candidat(ID_dossier))
