/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gestioncms;

/**
 *
 * @author Aicha pc
 */
public class CMSConsol extends javax.swing.JFrame {

    /**
     * Creates new form CMSConsol
     */
    public CMSConsol() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Candidat = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        Employé = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jTextField18 = new javax.swing.JTextField();
        jTextField19 = new javax.swing.JTextField();
        jTextField20 = new javax.swing.JTextField();
        jTextField21 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jTextField22 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox();
        jComboBox2 = new javax.swing.JComboBox();
        jTextField23 = new javax.swing.JTextField();
        jTextField24 = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jTextField26 = new javax.swing.JTextField();
        jTextField27 = new javax.swing.JTextField();
        jTextField28 = new javax.swing.JTextField();
        jTextField29 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        jTextField30 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField31 = new javax.swing.JTextField();
        jLabel55 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jLabel56 = new javax.swing.JLabel();
        jTextField39 = new javax.swing.JTextField();
        jLabel57 = new javax.swing.JLabel();
        jTextField42 = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jComboBox6 = new javax.swing.JComboBox();
        Unité_Fonctionnelle = new javax.swing.JPanel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jTextField40 = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jTextField41 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        Fonction = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jTextField32 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField33 = new javax.swing.JTextField();
        jLabel43 = new javax.swing.JLabel();
        jTextField34 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField35 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        Visite_Medicale = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jTextField36 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jTextField37 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        Type_Visite_Med = new javax.swing.JPanel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jTextField38 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jButton6 = new javax.swing.JButton();
        jLabel54 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        Congé_maladie = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jTextField14 = new javax.swing.JTextField();
        jTextField15 = new javax.swing.JTextField();
        jTextField16 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        Candidat.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText("ID_Dossier");
        Candidat.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 100, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Candidat");
        Candidat.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 100, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Nom_Candidat");
        Candidat.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, -1, -1));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Prenom_Candidat");
        Candidat.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText("Date_naiss_Candidat");
        Candidat.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        Candidat.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, -1));
        Candidat.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 130, -1));
        Candidat.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 130, -1));
        Candidat.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 130, -1));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText("Adresse_Candidat");
        Candidat.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 50, -1, -1));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Poste_travail_Candidat");
        Candidat.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 80, -1, -1));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel13.setText("Date_Visite_Emb");
        Candidat.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, -1, -1));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setText("Resultat_Visite");
        Candidat.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 140, -1, -1));
        Candidat.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 50, 130, -1));
        Candidat.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 80, 130, -1));

        jTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField11ActionPerformed(evt);
            }
        });
        Candidat.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 110, 130, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Apte", "Apte avec réserve", "Inapte" }));
        Candidat.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 140, 130, -1));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Enregistrer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        Candidat.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, -1, -1));

        jTabbedPane1.addTab("Candidat", Candidat);

        Employé.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel25.setText("Employé");
        Employé.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, 110, 20));

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel21.setText("Mat_Emp");
        Employé.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 80, -1));

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setText("Nom_Emp");
        Employé.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 100, -1));

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel23.setText("Prenom_Emp");
        Employé.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 110, -1));

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel24.setText("Date_naiss_Emp");
        Employé.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 130, -1));

        jLabel26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel26.setText("Lieu_naiss_Emp");
        Employé.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 120, -1));
        Employé.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 60, 120, -1));
        Employé.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, 120, -1));
        Employé.add(jTextField19, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 120, -1));

        jTextField20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField20ActionPerformed(evt);
            }
        });
        Employé.add(jTextField20, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 150, 120, -1));
        Employé.add(jTextField21, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 120, -1));

        jLabel27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel27.setText("Adresse_Emp");
        Employé.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 120, -1));

        jLabel28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel28.setText("Etat_civil_Emp");
        Employé.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 120, -1));

        jLabel29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel29.setText("Sexe_Emp");
        Employé.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 130, 20));

        jLabel30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel30.setText("Poids_Emp");
        Employé.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 110, -1));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel31.setText("Taille_Emp");
        Employé.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 80, 20));
        Employé.add(jTextField22, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 210, 120, -1));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Célibataire", "Marié", "Divorcé(e)", "Veuf(v)" }));
        Employé.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 120, -1));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculin", "Féminin" }));
        Employé.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 120, -1));
        Employé.add(jTextField23, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 120, -1));
        Employé.add(jTextField24, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 120, -1));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel32.setText("Groupe_Sang_Emp");
        Employé.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 60, 150, 20));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "A", "B", "O", "AB" }));
        Employé.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, -1, -1));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel33.setText("RH");
        Employé.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, 40, 20));

        jLabel34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel34.setText("N_S_S_Emp");
        Employé.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 130, 20));

        jLabel35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel35.setText("Modalité_Exercice");
        Employé.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 120, 140, 20));

        jLabel36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel36.setText("Hor_travail_Emp");
        Employé.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 150, 130, 20));

        jLabel37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel37.setText("Date_Recrutement_Emp");
        Employé.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 180, 20));
        Employé.add(jTextField26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 120, -1));
        Employé.add(jTextField27, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 120, -1));
        Employé.add(jTextField28, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 120, 120, -1));
        Employé.add(jTextField29, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, 120, -1));

        jLabel38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel38.setText("Date_Départ_retraite");
        Employé.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, -1, 20));
        Employé.add(jTextField30, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 120, -1));

        jLabel39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel39.setText("Cas_Maladie");
        Employé.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 130, 20));
        Employé.add(jTextField31, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 120, -1));

        jLabel55.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel55.setText("Service_National");
        Employé.add(jLabel55, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 270, 150, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dégagé", "Sursitaire" }));
        Employé.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 270, 120, -1));

        jLabel56.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel56.setText("Tabagisme");
        Employé.add(jLabel56, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, 130, -1));
        Employé.add(jTextField39, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 300, 120, -1));

        jLabel57.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel57.setText("Affectation");
        Employé.add(jLabel57, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 80, 20));
        Employé.add(jTextField42, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 330, 120, -1));

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton8.setText("Enregistrer");
        Employé.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 390, -1, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "+", "-" }));
        Employé.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 60, -1, -1));

        jTabbedPane1.addTab("Employé", Employé);

        Unité_Fonctionnelle.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel51.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel51.setText("Unité_Fonctionnelle");
        Unité_Fonctionnelle.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, -1, -1));

        jLabel52.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel52.setText("Code_UF");
        Unité_Fonctionnelle.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, -1, -1));
        Unité_Fonctionnelle.add(jTextField40, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 122, -1));

        jLabel53.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel53.setText("Designation_UF");
        Unité_Fonctionnelle.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 140, -1, -1));
        Unité_Fonctionnelle.add(jTextField41, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 122, -1));

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton7.setText("Enregistrer");
        Unité_Fonctionnelle.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 180, -1, -1));

        jTabbedPane1.addTab("Unité_Fonctionnelle", Unité_Fonctionnelle);

        Fonction.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel40.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel40.setText("Fonction");
        Fonction.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 26, -1, -1));

        jLabel41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel41.setText("Code_Fonction");
        Fonction.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));
        Fonction.add(jTextField32, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 130, -1));

        jLabel42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel42.setText("Libellé_Fonction");
        Fonction.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(51, 107, -1, -1));
        Fonction.add(jTextField33, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 130, -1));

        jLabel43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel43.setText("Atelier");
        Fonction.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, -1, -1));
        Fonction.add(jTextField34, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 60, 130, -1));

        jLabel44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel44.setText("Nature de Risque");
        Fonction.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 100, -1, -1));
        Fonction.add(jTextField35, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 100, 130, -1));

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Enregistrer");
        Fonction.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 170, -1, -1));

        jTabbedPane1.addTab("Fonction", Fonction);

        Visite_Medicale.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel45.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel45.setText("Visite_Médicale");
        Visite_Medicale.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 28, -1, -1));
        Visite_Medicale.add(jTextField36, new org.netbeans.lib.awtextra.AbsoluteConstraints(174, 89, 128, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel46.setText("Num_Visite_Med");
        Visite_Medicale.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 89, -1, -1));

        jLabel47.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel47.setText("Date_Visite_Med");
        Visite_Medicale.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 134, -1, -1));
        Visite_Medicale.add(jTextField37, new org.netbeans.lib.awtextra.AbsoluteConstraints(173, 127, 129, -1));

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setText("Enregistrer");
        Visite_Medicale.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, -1, -1));

        jTabbedPane1.addTab("Visite_Médicale", Visite_Medicale);

        Type_Visite_Med.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel48.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel48.setText("Type_Visite_Medicale");
        Type_Visite_Med.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 20, -1, -1));

        jLabel49.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel49.setText("Code_Type_Visite");
        Type_Visite_Med.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));
        Type_Visite_Med.add(jTextField38, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 120, -1));

        jLabel50.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel50.setText("Designation_Type_Visite");
        Type_Visite_Med.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, -1, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Périodique", "Reprise", "Spontanée", "Prolongation" }));
        Type_Visite_Med.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 120, -1));

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("Enregistrer");
        Type_Visite_Med.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, -1, -1));

        jLabel54.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel54.setText("Type_Visite_secondaire");
        Type_Visite_Med.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Aprés accident de travail", "Aprés maladie professionnelle", "Aprés congé maternité", "Aprés absence plus de 21 jours ou répétée" }));
        Type_Visite_Med.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 180, 280, -1));

        jTabbedPane1.addTab("Type_Visite_Med", Type_Visite_Med);

        Congé_maladie.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Enregistrer");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        Congé_maladie.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, 30));

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 51, 51));
        jLabel15.setText("    Congé_maladie");
        Congé_maladie.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, -1, -1));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel16.setText("Code_congé");
        Congé_maladie.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 110, 50));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel17.setText("Date_congé");
        Congé_maladie.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 100, 50));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel18.setText("Nbr_jour");
        Congé_maladie.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 90, 50));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel19.setText("Obs_congé");
        Congé_maladie.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 30, 110, 50));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel20.setText("Date_reprise");
        Congé_maladie.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 110, 50));
        Congé_maladie.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 50, 130, -1));
        Congé_maladie.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 130, -1));
        Congé_maladie.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 130, -1));
        Congé_maladie.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 40, 130, -1));
        Congé_maladie.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 80, 130, -1));

        jTabbedPane1.addTab("Congé maladie", Congé_maladie);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("ID_AT");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 63, -1, -1));

        jLabel1.setBackground(new java.awt.Color(255, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Accident_Travail");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 11, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Date_AT");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 106, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("Heure_AT");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 152, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setText("Date_Reprise");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 190, -1, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 63, 143, -1));
        jPanel1.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 106, 143, -1));
        jPanel1.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 152, 143, -1));
        jPanel1.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(152, 190, 143, -1));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Enregistrer");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 220, -1, -1));

        jTabbedPane1.addTab("Accident Travail", jPanel1);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 830, 490));
        getContentPane().add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField11ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jTextField20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField20ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CMSConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CMSConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CMSConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CMSConsol.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CMSConsol().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Candidat;
    private javax.swing.JPanel Congé_maladie;
    private javax.swing.JPanel Employé;
    private javax.swing.JPanel Fonction;
    private javax.swing.JPanel Type_Visite_Med;
    private javax.swing.JPanel Unité_Fonctionnelle;
    private javax.swing.JPanel Visite_Medicale;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox4;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField19;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField20;
    private javax.swing.JTextField jTextField21;
    private javax.swing.JTextField jTextField22;
    private javax.swing.JTextField jTextField23;
    private javax.swing.JTextField jTextField24;
    private javax.swing.JTextField jTextField26;
    private javax.swing.JTextField jTextField27;
    private javax.swing.JTextField jTextField28;
    private javax.swing.JTextField jTextField29;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField30;
    private javax.swing.JTextField jTextField31;
    private javax.swing.JTextField jTextField32;
    private javax.swing.JTextField jTextField33;
    private javax.swing.JTextField jTextField34;
    private javax.swing.JTextField jTextField35;
    private javax.swing.JTextField jTextField36;
    private javax.swing.JTextField jTextField37;
    private javax.swing.JTextField jTextField38;
    private javax.swing.JTextField jTextField39;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField40;
    private javax.swing.JTextField jTextField41;
    private javax.swing.JTextField jTextField42;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables
}
